---
apiVersion: v1
kind: Service
metadata:
  name: my-service
  namespace: default
spec:
  ports:
  - name: port-a
    port: 4455
    protocol: TCP
    targetPort: 4455
  - name: port-b
    port: 4456
    protocol: TCP
    targetPort: 4456
  sessionAffinity: None
  clusterIP: None
  type: ClusterIP

---
apiVersion: v1
kind: Endpoints
metadata:
  name: my-service-a
  namespace: default
subsets:
  - addresses:
    - ip: 10.237.121.204
    ports:
    - name: port-a
      port: 4455
      protocol: TCP

---
apiVersion: v1
kind: Endpoints
metadata:
  name: my-service-b
  namespace: default
subsets:
  - addresses:
    - ip: 10.237.121.204
    ports:
    - name: port-b
      port: 4456
      protocol: TCP
